services:
  db:
    container_name: jubelio-db
    image: postgres@sha256:f4b0987cb4ba8bcc2b90aa33ad8b5786669bec4dc633fc93d1418275e3627b34
    environment:
      POSTGRES_USER: jubelio
      POSTGRES_PASSWORD: jubelio
      POSTGRES_DB: jubelio
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data: